Repository btcsuite/btcd, pull requests merged in 2020-03, with the labels that each got.

#1537 Remove $GOPATH Caching
  .travis.yml
Labels: bug, build

#1213 Fix minRelayTxFee name in comment
  mempool/policy.go
Labels: documentation

#1507 release: add missing back tick in build docs
  release/README.md
Labels: bug, documentation, low priority

#1475 peer: fix small typo
  peer/peer.go
Labels: bug, documentation, low priority

#1398 Fix comment error
  database/ffldb/interface_test.go
Labels: bug, documentation, low priority

#1440 fix comment of database.Tx to match code
  database/ffldb/db.go
Labels: documentation, low priority

#1446 btcjson, rpclient: Fix typo
  btcjson/jsonrpc.go
  rpcclient/doc.go
Labels: documentation, low priority

#1382 blockchain/indexers: Start a new line for long code
  blockchain/indexers/addrindex.go
Labels: low priority

#1270 docs/json_rpc_api: update go examples
  docs/json_rpc_api.md
Labels: documentation, low priority

#1221 Add note about using gencerts when listening on specific interfaces
  docs/configure_peer_server_listen_interfaces.md
Labels: documentation, low priority

#1509 BUG:dynamicbanscore deadlock
  connmgr/dynamicbanscore.go
  connmgr/dynamicbanscore_test.go
Labels: bug, high priority

#1541 btcjson: add RPC_IN_WARMUP error code
  btcjson/jsonrpcerr.go
Labels: bug, low priority

#1529 Refactor GetBlockVerboseTx to reflect correct getblock RPC call parameters.
  btcjson/chainsvrcmds.go
  btcjson/chainsvrcmds_test.go
  btcjson/chainsvrresults.go
  btcjson/cmdinfo_test.go
  btcjson/example_test.go
  rpcclient/chain.go
  rpcserver.go
  rpcserverhelp.go
Labels: high priority, rpc

#1291 btcjson,rpcclient: use proper Deprecated comment format
  btcjson/chainsvrwscmds.go
  btcjson/chainsvrwsntfns.go
  rpcclient/notify.go
Labels: enhancement, low priority

#1524 update GetMempoolEntryResult to v0.19.0
  btcjson/chainsvrresults.go
Labels: bug, low priority

#1500 Add generatetoaddress and estimatesmartfee RPC calls
  btcjson/btcdextcmds.go
  btcjson/btcdextcmds_test.go
  btcjson/chainsvrresults.go
  btcjson/walletsvrcmds.go
  btcjson/walletsvrcmds_test.go
  rpcclient/chain.go
  rpcclient/mining.go
Labels: enhancement, high priority, rpc

#1491 Implement 'getblockstats' JSON-RPC command
  btcjson/chainsvrcmds.go
  btcjson/chainsvrcmds_test.go
  btcjson/chainsvrresults.go
  rpcclient/chain.go
Labels: enhancement, low priority, rpc

#1292 cmd/btcctl: use regexp.MustCompile for constant patterns
  cmd/btcctl/config.go
Labels: enhancement, low priority

#1502 Try both TX serialization formats in createrawtransaction
  rpcclient/rawtransactions.go
Labels: bug, enhancement, high priority
