Repository btcsuite/btcd, pull requests merged in 2021-09, with the labels that each got.

#1457 rpcclient: Export symbols needed for custom commands
  rpcclient/chain.go
  rpcclient/examples/customcommand/README.md
  rpcclient/examples/customcommand/main.go
  rpcclient/extensions.go
  rpcclient/infrastructure.go
  rpcclient/mining.go
  rpcclient/net.go
  rpcclient/notify.go
  rpcclient/rawrequest.go
  rpcclient/rawtransactions.go
  rpcclient/wallet.go
Labels: enhancement

#1742 mempool: introduce GetDustThreshold to export dust limit calculation
  mempool/policy.go
Labels: mempool

#1755 Upgraded the docker version to 1.16
  Dockerfile
Labels: build
